url: https://monikamimi.github.io
baseurl: 
host: 0.0.0.0
port: 4000
# exclude: [_raw_img]

# Site settings
title: Urocza ja
email: uroczaja@o2.pl
description: "Stylistyka i piercing"


# Team names, titles and social links
people:
- name: Monika Drozdowska
  pic: 1
  position: Lead Designer
  social:
    - title: facebook
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/Urocza-Ja-248618859014037/

# Postal address (add as many lines as necessary)
address:
  - line: Wrocław

# Build settings
markdown: kramdown
permalink: pretty