url: https://monikamimi.github.io
baseurl: 

# Site settings
title: Urocza ja
email: uroczaja@o2.pl
description: "Kosmetyka i piercing"


# Team names, titles and social links
people:
- name: Monika Drozdowska
  pic: 1
  position: Lead Designer
  social:
    - title: facebook
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: Wrocław

# Build settings
markdown: kramdown
permalink: pretty